name: Deploy GH Pages

on:
  push:
    branches: main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup project
        run: |
          cd falco-playground
          npm install
      - name: Build project
        run: |
          cd falco-playground
          CI=false npm run build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: falco-playground/build
    
